version: '3.1'

services:

  ddvis:
    image: quay.io/victorskl/ddvis
    container_name: ddvis
    volumes:
      - ./schema:/usr/share/nginx/html/schema:ro
    ports:
      - 8080:80

  g3po:
    image: quay.io/victorskl/g3po
    command: [ "tail", "-f", "/dev/null" ]
    container_name: g3po
    volumes:
      - ./schema:/schema:rw
      - ./dictionary:/dictionary:rw

  postgres:
    image: postgres:9.6
    container_name: ddpostgres
    ports:
      - 5432:5432
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./sql:/sql
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres

  dmutils:
    image: quay.io/victorskl/datamodelutils
    container_name: dmutils
    command: [ "tail", "-f", "/dev/null" ]
    environment:
      PG_HOST: postgres
      PG_USER: metadata
      PG_PASS: metadata
      PG_NAME: metadata

  ddsim:
    image: quay.io/cdis/data-simulator:1.3.3
    container_name: ddsim
    command: [ "tail", "-f", "/dev/null" ]
    volumes:
    - ./data:/data

  importer:
    container_name: importer
    command: [ "tail", "-f", "/dev/null" ]
    environment:
      PG_HOST: postgres
      PG_USER: metadata
      PG_PASS: metadata
      PG_NAME: metadata
      PSQL: "psql -h postgres -d metadata -U metadata"
      PGPASSWORD: metadata
    build:
      context: ./importer
    volumes:
      - ./output:/importer/output:rw
      - ./data:/importer/data:ro
      - ./schema:/importer/schema:ro
